version: '3.8'
services:
  dev-db:
    image: mysql:latest
    ports:
      - 4040:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=changas
    networks:
      - changasapp
networks:
  changasapp:
      